---
title: "No Supervisado"
author: "Pamela Pairo"
date: "11/17/2021"
output: html_document
---

```{r setup, include= FALSE}

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)

library(tidyverse)
library(palmerpenguins)
library(factoextra)
```

```{r}
glimpse(penguins)
```

```{r}
df <- na.omit(penguins) %>% 
          select(!where(is.factor) & -year)
```

```{r}
df <- scale(df)
head (df)
```

```{r}
k2 <- kmeans(df, centers = 2)
```

```{r}
fviz_cluster(k2, data = df, geom = c("point"))
```
```{r}
k3 <- kmeans(df, centers = 3)
k4 <- kmeans(df, centers = 4)
k5 <- kmeans(df, centers = 5)

# plots to compare
p1 <- fviz_cluster(k2, geom = "point", data = df) + ggtitle("k = 2")
p2 <- fviz_cluster(k3, geom = "point",  data = df) + ggtitle("k = 3")
p3 <- fviz_cluster(k4, geom = "point",  data = df) + ggtitle("k = 4")
p4 <- fviz_cluster(k5, geom = "point",  data = df) + ggtitle("k = 5")

library(gridExtra)
grid.arrange(p1, p2, p3, p4, nrow = 2)
```

#Método del codo

```{r}
fviz_nbclust(df, kmeans, method = "wss")
```

